# Generated by Django 5.0.3 on 2024-03-13 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('passphrese', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Slaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ip', models.GenericIPAddressField()),
                ('superuser', models.BooleanField()),
                ('last_report', models.DateField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kerb3ruX.masters')),
            ],
        ),
    ]
