# Generated by Django 5.0.3 on 2024-03-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kerb3ruX', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masters',
            new_name='Master',
        ),
        migrations.RenameModel(
            old_name='Slaves',
            new_name='Slave',
        ),
    ]
